export default [
  { name: "Amar Gambit", eco: "A00" },
  { name: "Amar Opening", eco: "A00" },
  { name: "Amsterdam Attack", eco: "A00" },
  { name: "Anderssen Opening", eco: "A00" },
  { name: "Barnes Opening", eco: "A00" },
  { name: "Clemenz Opening", eco: "A00" },
  { name: "Crab Opening", eco: "A00" },
  { name: "Creepy Crawly Formation", eco: "A00" },
  { name: "Englund Gambit Declined", eco: "A00" },
  { name: "Formation", eco: "A00" },
  { name: "Gedult's Opening", eco: "A00" },
  { name: "Global Opening", eco: "A00" },
  { name: "Grob Opening", eco: "A00" },
  { name: "Hungarian Opening", eco: "A00" },
  { name: "Indian Game", eco: "A00" },
  { name: "Kadas Opening", eco: "A00" },
  { name: "Lasker Simul Special", eco: "A00" },
  { name: "Mieses Opening", eco: "A00" },
  { name: "Polish Opening", eco: "A00" },
  { name: "Saragossa Opening", eco: "A00" },
  { name: "Sodium Attack", eco: "A00" },
  { name: "Valencia Opening", eco: "A00" },
  { name: "Van Geet Opening", eco: "A00" },
  { name: "Van't Kruijs Opening", eco: "A00" },
  { name: "Venezolana Opening", eco: "A00" },
  { name: "Ware Opening", eco: "A00" },
  { name: "Zukertort Opening", eco: "A00" },
  { name: "Nimzo-Larsen Attack", eco: "A01" },
  { name: "Nimzowitsch-Larsen Attack", eco: "A01" },
  { name: "Bird Opening", eco: "A02" },
  { name: "System", eco: "A02" },
  { name: "Colle System", eco: "A04" },
  { name: "Modern Defense", eco: "A04" },
  { name: "King's Indian Attack", eco: "A05" },
  { name: "English Opening", eco: "A07" },
  { name: "Réti Opening", eco: "A09" },
  { name: "King's Indian Defense", eco: "A10" },
  { name: "Horwitz Defense", eco: "A13" },
  { name: "English Orangutan", eco: "A15" },
  { name: "Australian Defense", eco: "A40" },
  { name: "Benoni Defense", eco: "A40" },
  { name: "Borg Defense", eco: "A40" },
  { name: "English Defense", eco: "A40" },
  { name: "Englund Gambit", eco: "A40" },
  { name: "Englund Gambit Complex Declined", eco: "A40" },
  { name: "Englund Gambit Complex", eco: "A40" },
  { name: "Kangaroo Defense", eco: "A40" },
  { name: "Mikenas Defense", eco: "A40" },
  { name: "Montevideo Defense", eco: "A40" },
  { name: "Polish Defense", eco: "A40" },
  { name: "Pterodactyl Defense", eco: "A40" },
  { name: "Queen's Pawn Game", eco: "A40" },
  { name: "Slav Indian", eco: "A40" },
  { name: "St. George Defense", eco: "A40" },
  { name: "Zaire Defense", eco: "A40" },
  { name: "Zukertort Defense", eco: "A40" },
  { name: "English Rat", eco: "A41" },
  { name: "King's Pawn Game", eco: "A41" },
  { name: "Old Indian Defense", eco: "A41" },
  { name: "Rat Defense", eco: "A41" },
  { name: "Robatsch Defense", eco: "A41" },
  { name: "Wade Defense", eco: "A41" },
  { name: "Amazon Attack", eco: "A45" },
  { name: "Blackmar-Diemer Gambit Declined", eco: "A45" },
  { name: "Bronstein Gambit", eco: "A45" },
  { name: "Canard Opening", eco: "A45" },
  { name: "Paleface Attack", eco: "A45" },
  { name: "Trompowsky Attack", eco: "A45" },
  { name: "Döry Defense", eco: "A46" },
  { name: "Torre Attack", eco: "A46" },
  { name: "Yusupov-Rubinstein System", eco: "A46" },
  { name: "Marienbad System", eco: "A47" },
  { name: "Queen's Indian Defense", eco: "A47" },
  { name: "East Indian Defense", eco: "A48" },
  { name: "London System", eco: "A48" },
  { name: "Indian Game: Przepiorka Variation", eco: "A49" },
  { name: "Mexican Defense", eco: "A50" },
  { name: "Indian Game: Medusa Gambit", eco: "A50" },
  { name: "Indian Game: Normal Variation", eco: "A50" },
  { name: "Queen's Indian Accelerated", eco: "A50" },
  { name: "Vulture Defense", eco: "A56" },
  { name: "Benko Gambit", eco: "A57" },
  { name: "Benko Gambit Accepted", eco: "A57" },
  { name: "Benko Gambit Declined", eco: "A57" },
  { name: "Benoni Defense: Classical Variation, Czerniak Defense", eco: "A79" },
  { name: "Blackmar-Diemer Gambit", eco: "A80" },
  { name: "Dutch Defense", eco: "A80" },
  { name: "Dutch Defense: Leningrad Variation", eco: "A86" },
  { name: "Dutch Defense: Classical Variation", eco: "A99" },
  { name: "Barnes Defense", eco: "B00" },
  { name: "Borg Opening", eco: "B00" },
  { name: "Carr Defense", eco: "B00" },
  { name: "Duras Gambit", eco: "B00" },
  { name: "Fried Fox Defense", eco: "B00" },
  { name: "Goldsmith Defense", eco: "B00" },
  { name: "Guatemala Defense", eco: "B00" },
  { name: "Hippopotamus Defense", eco: "B00" },
  { name: "King's Pawn", eco: "B00" },
  { name: "Lemming Defense", eco: "B00" },
  { name: "Lion Defense", eco: "B00" },
  { name: "Nimzowitsch Defense", eco: "B00" },
  { name: "Nimzowitsch Defense, Declined Variation", eco: "B00" },
  { name: "Owen Defense", eco: "B00" },
  { name: "Pirc Defense", eco: "B00" },
  { name: "Ware Defense", eco: "B00" },
  { name: "Scandinavian Defense", eco: "B01" },
  { name: "Alekhine Defense", eco: "B02" },
  { name: "Norwegian Defense", eco: "B06" },
  { name: "Czech Defense", eco: "B07" },
  { name: "Philidor Defense", eco: "B07" },
  { name: "Pirc Defense: Austrian Attack", eco: "B09" },
  { name: "Caro-Kann Defense", eco: "B10" },
  { name: "Slav Defense", eco: "B10" },
  { name: "Nimzo-Indian Defense", eco: "B14" },
  { name: "Sicilian Defense", eco: "B20" },
  { name: "French Defense", eco: "C00" },
  { name: "Bongcloud Attack", eco: "C20" },
  { name: "Center Game", eco: "C20" },
  { name: "King's Pawn Opening", eco: "C20" },
  { name: "Portuguese Opening", eco: "C20" },
  { name: "Center Game Accepted", eco: "C21" },
  { name: "Danish Gambit", eco: "C21" },
  { name: "Danish Gambit Accepted", eco: "C21" },
  { name: "Danish Gambit Declined", eco: "C21" },
  { name: "Bishop's Opening", eco: "C23" },
  { name: "Vienna Game", eco: "C25" },
  { name: "King's Gambit", eco: "C30" },
  { name: "King's Gambit Declined", eco: "C30" },
  { name: "King's Gambit Accepted", eco: "C33" },
  { name: "Elephant Gambit", eco: "C40" },
  { name: "Gunderam Defense", eco: "C40" },
  { name: "King's Knight Opening", eco: "C40" },
  { name: "Latvian Gambit", eco: "C40" },
  { name: "Latvian Gambit Accepted", eco: "C40" },
  { name: "Russian Game", eco: "C42" },
  { name: "Dresden Opening", eco: "C44" },
  { name: "Irish Gambit", eco: "C44" },
  { name: "Ponziani Opening", eco: "C44" },
  { name: "Scotch Game", eco: "C44" },
  { name: "Tayler Opening", eco: "C44" },
  { name: "Four Knights Game", eco: "C46" },
  { name: "Three Knights Opening", eco: "C46" },
  { name: "Blackburne Shilling Gambit", eco: "C50" },
  { name: "Giuoco Piano", eco: "C50" },
  { name: "Italian Game", eco: "C50" },
  { name: "Ruy Lopez", eco: "C60" },
  { name: "Blackmar Gambit", eco: "D00" },
  { name: "Blackmar-Diemer, Lemberger Countergambit", eco: "D00" },
  { name: "Rapport-Jobava System", eco: "D01" },
  { name: "Richter-Veresov Attack", eco: "D01" },
  { name: "Veresov Opening", eco: "D01" },
  { name: "Queen's Gambit Accepted", eco: "D02" },
  { name: "Queen's Gambit Declined", eco: "D02" },
  { name: "Queen's Pawn Game, Zukertort Variation", eco: "D05" },
  { name: "Rubinstein Opening", eco: "D05" },
  { name: "Queen's Gambit", eco: "D06" },
  { name: "Semi-Slav Defense", eco: "D30" },
  { name: "Tarrasch Defense", eco: "D32" },
  { name: "Semi-Slav Defense Accepted", eco: "D44" },
  { name: "Neo-Grünfeld Defense", eco: "D70" },
  { name: "Grünfeld Defense", eco: "D80" },
  { name: "Catalan Opening", eco: "E00" },
  { name: "Blumenfeld Countergambit", eco: "E10" },
  { name: "Blumenfeld Countergambit Accepted", eco: "E10" },
  { name: "Bogo-Indian Defense", eco: "E11" },
  { name: "Queen's Indian, Averbakh Variation", eco: "E14" },
  { name: "Queen's Indian, Buerger Variation", eco: "E15" },
  { name: "Nimzo-Indian Defense, Ragozin Variation", eco: "E51" },
  { name: "Queen's Pawn, Mengarini Attack", eco: "E60" },
  {
    name: "King's Indian Defense, Fianchetto Variation, Classical Variation",
    eco: "E68",
  },
  { name: "King's Indian, Averbakh, Main Line", eco: "E75" },
  { name: "King's Indian, Sämisch, Ruban Variation", eco: "E83" },
  { name: "King's Indian, Sämisch, Panno Main Line", eco: "E84" },
];
